<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TVMATP407267D" name="com.keurig.testing.webservicetesting.AppTestcopy" tests="1" failures="1" timestamp="2 Dec 2016 10:14:58 GMT" time="5.637" errors="0">
  <testcase name="verifyPerfectCup" time="5.637" classname="com.keurig.testing.webservicetesting.AppTestcopy">
    <failure type="java.lang.AssertionError" message="expected [ Daybreak-Morning-Blend-Coffee-K-Cup-Caribou] but found [ Donut-House-Extra-Bold-Coffee-K-Cup-Donut-House]">
      <![CDATA[java.lang.AssertionError: expected [ Daybreak-Morning-Blend-Coffee-K-Cup-Caribou] but found [ Donut-House-Extra-Bold-Coffee-K-Cup-Donut-House]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.keurig.testing.webservicetesting.RestServiceCopy.validateSensoryResponse(RestServiceCopy.java:36)
	at com.keurig.testing.webservicetesting.AppTestcopy.verifyPerfectCup(AppTestcopy.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- verifyPerfectCup -->
</testsuite> <!-- com.keurig.testing.webservicetesting.AppTestcopy -->
